### ISSUE TITLE
Deprecated selector in `zebra-stripes\styles\zebra-stripes.less`

### ISSUE THREAD

**Issue by MaximDmitrievich** [prodigic/zebra-stripes#1]
In `zebra-stripes\styles\zebra-stripes.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.zebra-stripes.theme-my-syntax-dark-theme atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-atom-dark-syntax atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-monokai-seti atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-base16-tomorrow-dark-theme atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-one-dark-syntax atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-solarized-dark-syntax atom-text-editor::shadow .line:nth-child(odd)` => `.zebra-stripes.theme-my-syntax-dark-theme atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-atom-dark-syntax atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-monokai-seti atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-base16-tomorrow-dark-theme atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-one-dark-syntax atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-solarized-dark-syntax atom-text-editor.editor .line:nth-child(odd)`

* `.zebra-stripes.theme-my-syntax-light-theme atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-base16-tomorrow-light-theme atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-one-light-syntax atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-solarized-light-syntax atom-text-editor::shadow .line:nth-child(odd),
.zebra-stripes.theme-atom-light-syntax atom-text-editor::shadow .line:nth-child(odd)` => `.zebra-stripes.theme-my-syntax-light-theme atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-base16-tomorrow-light-theme atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-one-light-syntax atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-solarized-light-syntax atom-text-editor.editor .line:nth-child(odd),
.zebra-stripes.theme-atom-light-syntax atom-text-editor.editor .line:nth-child(odd)`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by prodigic** [comment]
fixed in next release
